# SERVER
server.port=${PORT:8084}
spring.application.name=api-multinivel

# DATABASE
spring.datasource.url=${DB_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:visanaco_produc}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD}

# JPA & HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

# SECURITY & KEYCLOAK
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/visana-erp}

# API FOUNDATION
visana.api.cors-allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

# OBSERVABILITY
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.endpoints.web.base-path=/actuator
management.endpoint.env.enabled=false
management.endpoint.beans.enabled=false
management.endpoint.configprops.enabled=false
management.endpoint.mappings.enabled=false
