spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}
visana.security.health-client-id=${DEV_HEALTHCHECK_CLIENT_ID}
visana.security.health-subject=${DEV_HEALTHCHECK_SUBJECT}
visana.security.health-audience=${DEV_HEALTHCHECK_AUDIENCE}
