package com.visana.erp.network.foundation.application;
import com.visana.erp.network.foundation.domain.*;
import com.visana.erp.network.foundation.infrastructure.persistence.*;
import com.visana.erp.platform.application.audit.AuditEventWriter;
import com.visana.erp.platform.domain.audit.AuditEvent;
import java.time.Instant; import java.util.*;
import org.slf4j.MDC; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class NetworkFoundationService {
 private final BusinessProfileRepository profiles; private final BusinessProfileActorLinkRepository links; private final NetworkMemberRepository members; private final SponsorRelationshipRepository relationships; private final JdbcTemplate jdbc; private final AuditEventWriter audit;
 public NetworkFoundationService(BusinessProfileRepository p,BusinessProfileActorLinkRepository l,NetworkMemberRepository m,SponsorRelationshipRepository r,JdbcTemplate j,AuditEventWriter a){profiles=p;links=l;members=m;relationships=r;jdbc=j;audit=a;}
 @Transactional public NetworkMember establishMemberForActor(UUID actorId){ if(links.findByActorId(actorId).isPresent()) throw new IllegalStateException("actor already has an explicitly linked business profile"); Instant now=Instant.now(); UUID profile=UUID.randomUUID(), member=UUID.randomUUID();profiles.save(new BusinessProfileJpaEntity(profile,actorId,now));links.save(new BusinessProfileActorLinkJpaEntity(UUID.randomUUID(),profile,actorId,now));members.save(new NetworkMemberJpaEntity(member,profile,now));jdbc.update("insert into genealogy_closure(ancestor_member_id,descendant_member_id,depth) values (?,?,0)",member,member);audit("BUSINESS_PROFILE_LINK",actorId,profile);audit("NETWORK_MEMBER_CREATED",actorId,member);return new NetworkMember(member,profile,NetworkMember.RecordStatus.RECORD_ACTIVE,now); }
 @Transactional public SponsorRelationship assignInitialSponsor(UUID actorId,UUID sponsor,UUID member){ if(sponsor.equals(member)){audit("NETWORK_CYCLE_REJECTED",actorId,member);throw new IllegalArgumentException("a member cannot sponsor itself");} if(!members.existsById(sponsor)||!members.existsById(member)) throw new IllegalArgumentException("network member was not found"); if(relationships.existsByMemberId(member)){audit("SPONSOR_CHANGE_DENIED",actorId,member);throw new NetworkOperationForbiddenException("sponsor change is blocked pending business decision");} Integer cycle=jdbc.queryForObject("select count(*) from genealogy_closure where ancestor_member_id=? and descendant_member_id=?",Integer.class,member,sponsor);if(cycle!=null&&cycle>0){audit("NETWORK_CYCLE_REJECTED",actorId,member);throw new IllegalArgumentException("sponsor relationship would create a cycle");} Instant now=Instant.now();SponsorRelationship relation=new SponsorRelationship(UUID.randomUUID(),sponsor,member,now,now);relationships.save(new SponsorRelationshipJpaEntity(relation.id(),sponsor,member,now));jdbc.update("insert into genealogy_closure(ancestor_member_id,descendant_member_id,depth) select ancestor_member_id, ?, depth + 1 from genealogy_closure where descendant_member_id=?",member,sponsor);audit("SPONSOR_ASSIGNED",actorId,relation.id());return relation; }
 @Transactional(readOnly=true) public UUID memberForActor(UUID actor){return links.findByActorId(actor).flatMap(link->members.findByBusinessProfileId(link.profile())).map(NetworkMemberJpaEntity::id).orElseThrow(()->new NetworkOperationForbiddenException("business profile or network membership is not linked"));}
 @Transactional(readOnly=true) public List<MemberDepth> ancestors(UUID member,int limit){return query("select ancestor_member_id, depth from genealogy_closure where descendant_member_id=? and depth>0 order by depth asc limit ?",member,limit);}
 @Transactional(readOnly=true) public List<MemberDepth> descendants(UUID member,int limit){return query("select descendant_member_id, depth from genealogy_closure where ancestor_member_id=? and depth>0 order by depth asc limit ?",member,limit);}
 @Transactional(readOnly=true) public List<UUID> direct(UUID sponsor,int limit){return jdbc.query("select member_id from sponsor_relationships where sponsor_member_id=? order by created_at asc limit ?",(rs,row)->UUID.fromString(rs.getString(1)),sponsor,limit);}
 private List<MemberDepth> query(String sql,UUID member,int limit){if(limit<1||limit>100)throw new IllegalArgumentException("limit must be between 1 and 100");return jdbc.query(sql,(rs,row)->new MemberDepth(UUID.fromString(rs.getString(1)),rs.getInt(2)),member,limit);} private void audit(String action,UUID actor,UUID resource){audit.append(new AuditEvent(actor.toString(),action,"NETWORK",resource.toString(),Instant.now(),Optional.ofNullable(MDC.get("correlationId")).orElse("system"),Map.of()));} public record MemberDepth(UUID memberId,int depth){}
}
